name: Laravel workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Laravel build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Composer Action
        uses: ./.github/actions/composer
