name: Laravel workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Laravel build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Composer Action
        uses: ./.github/actions/composer
      - name: Build laravel
        uses: ./.github/actions/conf-laravel
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
      - name: Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs


