name: Yarn Workflow
on:
  push:
    paths:
      - 'resources/js/*'

jobs:
  build:
    name: Yarn Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn run production
